version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpassword
      - POSTGRES_DB=persondb
    ports: 
      - "5432:5432"
  
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpassword"
    ports:
      - "80:80"
    depends_on:
      - postgres

