version: '3.7'
services:
  mysql_dev:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cinemadb
    ports:
      - "3308:3306"

  custom_mysql_cont:
    image: my_cinema_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3316:3306"
